using System.ComponentModel.DataAnnotations;

namespace JobPortalWebAPI.Models.Domain
{
    public class CompanyProfile
    {
        // Foreign Key + Primary Key (1-to-1 with ApplicationUser)
        [Key]
        public string? ApplicationUserId { get; set; } // Refers to string Id generated by ApplicationUser

        public string CompanyName { get; set; } =  string.Empty;
        public string CompanyLocation {  get; set; } = string.Empty;

        // Field for company Image
        public string? CompanyImagePath { get; set; }

        // Navigation to ApplicationUser
        public ApplicationUser? ApplicationUser { get; set; }

        // Navigation
        public ICollection<Job> PostedJobs { get; set; } = new List<Job>(); // Jobs posted by the respective company
    }
}
