using System.ComponentModel.DataAnnotations;

namespace JobPortalWebAPI.Models.Domain
{
    public class UserProfile
    {
        // Foreign Key + Primary Key (1-to-1 with ApplicationUser)
        [Key]
        public string? ApplicationUserId { get; set; } // Refers to string Id generated by ApplicationUser

        public string FullName { get; set; } =  string.Empty;
        public string MobileNumber { get; set; } = string.Empty;

        // Field for User Image
        public string? ProfileImagePath { get; set; }

        // Field for Resume file
        public string? ResumeFilePath { get; set; }

        // Navigation to ApplicationUser
        public ApplicationUser? ApplicationUser { get; set; }

        // Navigation Properties
        public ICollection<SavedJob> SavedJobs { get; set; } = new List<SavedJob>(); // jobs saved by the user
        public ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>(); // applied jobs by the user
    }
}
